import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat, Jost, Ubuntu, Ysabeau_SC } from 'next/font/google'


const montserrat = Montserrat({ 
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-montserrat'
})

const jost = Jost({ 
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-jost'
})


const ubuntu = Ubuntu({ 
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-ubuntu'
})


const ysabeau = Ysabeau_SC({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-ysabeau'
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ysabeau.variable} ${ubuntu.variable} ${jost.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
